### ISSUE TITLE
Jar file won't open

### ISSUE THREAD

**Issue by Wholesome-Souls** [zeobviouslyfakeacc/ModLoaderInstaller#11]
So, I've spent the last hour trying to figure this out. I downloaded the file, but didn't have java. So I downloaded Java 8, which should work, but when I try to open Jar files, like this one, it does nothing. I click, nothing happens. I've uninstalled and reinstalled Java, still no. I got winrar, which can open the jar file, but nothing in there is something I can execute to get the dialogue box I need. So what do I do?

**Comment by zeobviouslyfakeacc** [comment]
*I'm assuming you're using a recent version of Windows. please let me know if that isn't the case*

Hmm, that's a weird issue. Usually you should be able to launch the installer by simply executing the JAR file with your Java runtime.

However, installing WinRAR definitely won't help you here. WinRAR, for whatever reason, considers JAR files to be archive files. However, that's **wrong**. JAR files may look and feel like a ZIP archive, but they're actually executable files. The only thing WinRAR does is assign itself as the default application to open JAR files, which definitely isn't helpful.

So first of all, I'd like you to set the default application to open JAR files back to "Java(TM) Platform SE binary". If your "Open With" dialog don't have that entry, you may not have installed Java correctly, or you used the wrong installer for your operating system.

Second, it could be that the mod loader installer fails to launch because of some exception during its initialization. To find out what's wrong, let's launch it through a command prompt:
- Open a command prompt, e.g. by pressing Win+R to launch the "Run..." dialog, entering "cmd" and pressing enter.
- Set the current directory to the directory that contains ModLoaderInstaller.jar by using the "cd" command.
  - e.g. `cd /D C:\Users\YOUR_ACCOUNT_NAME_HERE\Downloads`
- Launch the mod loader installer with `java -jar ModLoaderInstaller.jar`

I'm interested to know what happens next. Do you see the installer window pop up, or does any error message appear in the command prompt?

**Comment by Wholesome-Souls** [comment]
You beauty! Did exactly what you said and it worked just like that! Thanks a bunch! c:
