### ISSUE TITLE
Mod loader no longer works on Hotfix 1.56 for Windows

### ISSUE THREAD

**Issue by Moichol** [zeobviouslyfakeacc/ModLoaderInstaller#22]
Every time mod loader patches the directory the game will refuse to get past the disclaimer screen because it gets hard stuck frozen. The only way to fix it is to verify the integrity of the game folders which pretty much reverses what  the mod loader did.

**Comment by zeobviouslyfakeacc** [comment]
Hi!

As far as I can tell, this is caused by one of your mods, and not by the mod loader itself.
Could you start your game with the mod loader installed, wait for it to crash / black screen, and then upload your log file here?

How to find your log file, assuming Windows:
- Press Win+R to open a run dialog
- Copy & paste `%AppData%\..\LocalLow\Hinterland\TheLongDark` and press enter
- Upload the file `output_log.txt` somewhere (e.g. pastebin, gist.github.com, etc.) and send me a link 😄

**Comment by Moichol** [comment]
[output_log.txt](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/files/3398960/output_log.txt)

**Comment by zeobviouslyfakeacc** [comment]
That's caused by AnkleSupport, which has not been updated for TLD v1.49 or newer yet, so you'll have to remove that mod. If you have BetterWaterManagement installed, too: that mod is also broken, and you'll also have to remove it.

Here's a list of which mods are currently working and which aren't: http://xpazeman.com/tld-mod-list/

**Comment by Moichol** [comment]
Thank you!, I was in the process of disabling mods, but I would have never thought to disable ankle support.
