### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by Warrot** [zeobviouslyfakeacc/ModLoaderInstaller#3]
The jar file cannot be guided to the correct path on macOS, because of the different path on mac.
It may be able to be solved if its possible to copy in the path instead of guiding the installer to it.

I think this problem was also posted in the post about the installer on /r/TheLongDark
Kudos, for making a modLoader :=)

**Comment by Dandymonkey** [comment]
Using MacOs:
Pathname does not match
Java will not allow me to unpack TLD contents to navigate to .dll file

**Comment by Augustrae** [comment]
Same here. Can not navigate to the .dll in order to patch. Please help. Want the same mods for my PC and Mac.

**Comment by zeobviouslyfakeacc** [comment]
Just now realized that I wasn't getting email notifications about new issues. Sorry everyone!

I've updated the mod loader to [version 1.2](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.2), which basically only contains UI fixes. Now you should also be able to select the `.app` directory instead of the DLL file. The mod loader will then work out the rest. This should be a workaround to not being able to select files inside these application folders.

Strangely enough, someone tested the installer v1.1 on their Mac and didn't report any trouble selecting a file inside a `.app` directory. Maybe this behavior only existed on some versions / configurations of macOS?

Either way, please let me know if this new version works fixed your issue! :smile:

**Comment by Augustrae** [comment]
Fixed. 1.2 worked perfectly.

**Comment by zeobviouslyfakeacc** [comment]
Phew, I'm relieved to hear this! Enjoy the mods :smile:

**Comment by Dandymonkey** [comment]
Same here, thanks so much. very smooth.
