### ISSUE TITLE
Modding The Long Dark on Mac

### ISSUE THREAD

**Issue by kdn5296** [zeobviouslyfakeacc/ModLoaderInstaller#7]
As suggested, I am posting my attempt to use mods on The Long Dark, on my Mac. I downloaded both the mod itself and the ModLauncher, however that is where I began to run into problems. I am not technologically illiterate, however I am not a whiz either, so my issues could very well be my own lack of knowledge. When I opened the mod launcher, it asked for the path to the DLL, which to my understanding is a Windows specific type of file. So when I clicked on the ellipses button to the right of the "Path to the DLL:" text box, I selected "TLD Executable" instead of "Rewired_Core.dll". However, despite following all instructions I could find that explained how to open mod launcher properly, I could not find or figure out which file the mod loader wanted, as the only example online is on Windows, which showed the "Rewired_Core.dll" file plain as day ready to be uploaded. I do not have this file, and even if I did I could not figure out how to supply the path to the Mod Loader. Because of this I am unable to load mods onto my game. Any help/feedback on this issue would be gratefully appreciated. 

Thank You, 
Kevin

**Comment by kdn5296** [comment]
Update: Was able to find correct path and the ModLauncher says "Valid, patched". However, when I reopen the The Long Dark folder, there is no "mod" folder to drag the mod into.

**Comment by zeobviouslyfakeacc** [comment]
Hi @kdn5296!

If I didn't mess up, there should be a mods folder next to the application file that you had selected when installing the mod loader.

That means, assuming the path to the executable was
`some/folder/structure/Steam/SteamApps/common/TheLongDark/tld.app`
and the path to the DLL (which seems to be inaccessible to you, because Apple likes to keep their users away from anything even remotely technical) was
`some/folder/structure/Steam/SteamApps/common/TheLongDark/tld.app/Contents/Resources/Data/Managed/Rewired_Core.dll`,
then there should now be a mods folder at
`some/folder/structure/Steam/SteamApps/common/TheLongDark/mods`

If that folder doesn't exist, I'd be glad if you could re-run the installer application and select the TLD executable once more. Then, first remove and then re-patch the mod loader by simply pressing the patch / unpatch button twice. What I'm interested in is the text that appears in the lower left corner of the application after installing the mod loader.

If it simply says "Done!", that indicates that there were at least no exceptions when copying the libraries and creating the mods folder. In other words, there should be a mods folder somewhere, but it may either be in the wrong place, or you're maybe not looking for it in the right place 😜 

On the other hand, if it says "The game was successfully patched, but copying libraries failed." (or something else entirely), that would indicate that something messed up and would open up a way to investigate further.

You also mentioned that:
> When I opened the mod launcher, it asked for the path to the DLL, which to my understanding is a Windows specific type of file.

Correct, DLLs are usually only used on Windows. However, Unity games ship with a software called Mono, which also runs C# assemblies (e.g. in DLLs) on other operating systems.

Moreover, I should probably improve my GUI :smile:

**Comment by kdn5296** [comment]
Great. I will try it as soon as I get home. Thanks for the quick response!


Thank You, Kevin Nelms

**Comment by kdn5296** [comment]
Hi, turns out you didn't mess up at all. When I was selecting the path for
the file to patch in the mod loader, as you said Apple was making it very
difficult to find the actual "The Long Dark" .app file itself in Finder, so
I simply dragged it to my desktop to make it easier to locate when I was
searching within the mod loader. I was looking around for the mod folder
that should have been created within the game files itself, not next to the
folder as I should have. Then I realized that since I had earlier moved the
game folder to the desktop. When the mod loader patched and created the mod
folder, it was in fact next to the game folder, however it created it next
to the game file on the desktop, as it was told to do, since it creates the
mods folder next to the game file regardless of where the game folder is on
my computer. Which with all my digital illiteracy, I failed to realize.
Once I located the folder, I simply dragged the mod files, (dll and config
I think), which in this case was UModTLD, to the mod folder. After which I
fired up the game and everything worked as it should. The only thing that I
am having trouble with is figuring out how to open a command line within
the game to enter certain commands not accessible with hot keys and
shortcuts. The mod page says just enter the "/" key, but that is not
working. However, this of course has nothing to do with your mod loader,
which operated to perfection and would have been painless for pretty much
anyone but my dumb self, but all in all a successful experiment. Thank you
for your time and help with the issue, and the quick reply.

Kevin

**Comment by kdn5296** [comment]
*Correction "I was looking around for the mod folder that I thought was
created within the game files themselves, not next to the game file as I
should have"
:)

**Comment by zeobviouslyfakeacc** [comment]
I'm so happy that you were able to solve your issue (and quite relieved that I didn't mess up) :blush:

As for your issue with UMod, if I were you I'd probably first just mash all the keys on my keyboard and test whether any of them do anything 😋
If that doesn't help, you'll probably have to contact UberFoX or FINDarkside directly.

Cheers!

**Comment by kdn5296** [comment]
Once again it was user error. I was using forward slash next to shift key as opposed to backslash under delete key :) However the last problem, once again probably my error, but when I enter a command, no results come up or actions occur. I watched modders video and definitely doesn’t look like my screen, but we will see what they say. Not sure if I have to do something to make output visible. Maybe has something to do with me on a Mac, you never know, anyway, thank you so much for your help and time, not to mention creating the mod loader itself! 

Thank You, Kevin Nelms

**Comment by jflinders** [comment]
<img width="1284" alt="Ekran Resmi 2019-07-14 13 36 27" src="https://user-images.githubusercontent.com/52881937/61182516-021a3a80-a63d-11e9-9dd2-362d172fceb6.png">
<img width="818" alt="Ekran Resmi 2019-07-14 13 37 14" src="https://user-images.githubusercontent.com/52881937/61182517-02b2d100-a63d-11e9-871e-83548ab72e29.png">

I also manually "viewed the contents" of the long dark app directly in the finder to browse subfolders. As you can see there is no such file that the mod installer gave me the missing file error about.

Please instruct me on how to mod tld both via this mod installer or manually.

Currently the mods I've downloaded from github and wanted to install are the following ones:

1- Ankle-Support-master
2- Durable-Whetstone-master
3- HungerRevamped-master
4- TLD-Developer-Console-master
5- tld-GameTweaks-master

I'm on mac os latest mojave and ofc latest tld on steam.

**Comment by zeobviouslyfakeacc** [comment]
@jflinders See #18. Hinterland switched to a different scripting backend on Mac. In other words, no more mods for Mac until they switch back to Mono...
