### ISSUE TITLE
No longer working with newest test branch v1.24 34615 ?

### ISSUE THREAD

**Issue by aproposnix** [zeobviouslyfakeacc/ModLoaderInstaller#8]
It looks like there may be changes to the game which makes this MOD loader no longer work.  

When I try to patch the game I just see "INVALID" when I select the file for patching.  So, no mods for now :(

**Comment by zeobviouslyfakeacc** [comment]
Yeah, today's update shipped an updated version of Rewired, TLD's input library. Thus, `Rewired_Core.dll`, the file we hijack to load and start the mod loader, has been overwritten.

I wouldn't recommend using mods in this test branch anyways (unless you want to work on your own mods). Most mods are broken due to the Unity upgrade and some changes to TLD's code. Moreover, the test branch doesn't even contain any new features, so you're not gaining anything from using the test branch. I'd recommend either opting out of the beta and re-patching your game, or playing the test branch without mods installed.

I'll get the mod loader updated soon-ish. I still want to make some more changes to the installer GUI.
But I promise it'll be released by the time the full update is released.

**Comment by zeobviouslyfakeacc** [comment]
Got the mod loader [updated for TLD v1.27](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.3)!

Please let me know if anything doesn't work :blush:
